from AnalysisDesigner.Analyzer import Analyzer
from AnalysisDesigner.Analyzer_All import AnalyzerAll
from AnalysisDesigner.Analyzer_Selection import AnalyzerSel
from AnalysisDesigner.Selector import Selector
